[env]
CARGO_WORKSPACE_DIR = {value = "", relative=true}
CARGO_EXTRA_BIN_DIR = {value = ".bin", relative=true}
CARGO_EXTRA_BUILD_DIR = {value = ".build", relative=true}
CARGO_EXTRA_BUILD_FILE = ".build_data.json"
