on:
  push:
    branches:
      - master
  workflow_dispatch:

name: "Release Please"

jobs:

  release-please:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    outputs:

      ck3oop--id: ${{ steps.release-please.outputs['id'] }}
      ck3oop--tag: ${{ steps.release-please.outputs['tag_name'] }}
      ck3oop--created: ${{ steps.release-please.outputs['release_created'] }}

      ck3oop-core-js--id: ${{ steps.release-please.outputs['ck3oop-core-js--id'] }}
      ck3oop-core-js--tag: ${{ steps.release-please.outputs['ck3oop-core-js--tag_name'] }}
      ck3oop-core-js--created: ${{ steps.release-please.outputs['ck3oop-core-js--release_created'] }}

      ck3oop-core-rs--id: ${{ steps.release-please.outputs['ck3oop-core-rs--id'] }}
      ck3oop-core-rs--tag: ${{ steps.release-please.outputs['ck3oop-core-rs--tag_name'] }}
      ck3oop-core-rs--created: ${{ steps.release-please.outputs['ck3oop-core-rs--release_created'] }}

      ck3oop-ui--id: ${{ steps.release-please.outputs['ck3oop-ui--id'] }}
      ck3oop-ui--tag: ${{ steps.release-please.outputs['ck3oop-ui--tag_name'] }}
      ck3oop-ui--created: ${{ steps.release-please.outputs['ck3oop-ui--release_created'] }}

      ck3oop-ui/src-tauri--id: ${{ steps.release-please.outputs['ck3oop-ui/src-tauri--id'] }}
      ck3oop-ui/src-tauri--tag: ${{ steps.release-please.outputs['ck3oop-ui/src-tauri--tag_name'] }}
      ck3oop-ui/src-tauri--created: ${{ steps.release-please.outputs['ck3oop-ui/src-tauri--release_created'] }}

    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release-please
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: '.github/release-please-config.json'
          manifest-file: '.github/.release-please-manifest.json'

      - run: |
          echo '${{ toJSON(steps.release-please.outputs) }}'

  release-please-output:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(needs.release-please.outputs) }}'
    needs: [ release-please ]

  publish-core-rs:
    needs: [ release-please ]
    if: ${{ needs.release-please.outputs['ck3oop-core-rs--created'] }}
    uses: "./.github/workflows/rust-publish-crate.yaml"
    with:
      package: 'ck3oop-core-rs'
      tag: ${{ needs.release-please.outputs['ck3oop-core-rs--tag'] }}
    secrets:
      RUST_CRATES_TOKEN: ${{ secrets.RUST_CRATES_TOKEN }}

  publish-npm:
    needs: [ release-please ]
    if: ${{ needs.release-please.outputs['ck3oop-core-js--created'] }}
    uses: "./.github/workflows/npm-publish-package.yaml"
    with:
      package: 'ck3oop-core-js'
      tag: ${{ needs.release-please.outputs['ck3oop-core-js--tag'] }}
    secrets:
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}

  publish-tauri:
    permissions:
      contents: write
    needs: [ release-please ]
    if: ${{ needs.release-please.outputs['ck3oop--created'] }}
    uses: "./.github/workflows/tauri-publish-artifacts.yaml"
    with:
      id: ${{ needs.release-please.outputs['ck3oop--id'] }}
      tag: ${{ needs.release-please.outputs['ck3oop--tag'] }}
