name: "Rust: Test"

on:
  workflow_dispatch:
  workflow_call:

  push:
    branches:
      - master

  pull_request:

jobs:

  cargo-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # v1
        with:
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2
        with:
          cache-all-crates: true
          cache-targets: true
          cache-directories: |
            .bin

      - name: Install Tauri Dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run Cargo Test
        run: |
          cargo test -- --nocapture
