name: "Rust: Test"

on:
  workflow_dispatch:
  workflow_call:

  push:
    branches:
      - master

  pull_request:

env:
  JUST_UNSTABLE: true

jobs:

  cargo-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Just
        uses: extractions/setup-just@6e1de3cc407de738551abd6c0923bd5ed5608042
        with:
          just-version: 1.29.0

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # v1
        with:
          toolchain: stable

      - name: Install Deps
        run: |
          just prepare

      - name: Run Cargo Test
        run: |
          cargo test -- --nocapture
