name: "Rust: Test"

on:
  workflow_dispatch:
  workflow_call:

  push:
    branches:
      - master

  pull_request:

jobs:

  cargo-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Just
        uses: extractions/setup-just@6e1de3cc407de738551abd6c0923bd5ed5608042
        with:
          just-version: 1.29.0

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2
        with:
          cache-all-crates: true
          cache-targets: true
          cache-directories: |
            .build

      - name: Install Tauri Dependencies (ubuntu only)
        run: |
          sudo apt update
          . <(just prerequisites)

      - name: Run Cargo Test
        run: |
          cargo test -- --nocapture
