name: "Tauri: Publish Artifacts"

on:
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: 'ID of the release to publish'
        required: true
      tag:
        type: string
        description: 'Tag of the release to publish'
        required: true
  workflow_call:
    inputs:
      id:
        type: string
        description: 'ID of the release to publish'
        required: true
      tag:
        type: string
        description: 'Tag of the release to publish'
        required: true

env:
  JUST_UNSTABLE: true

jobs:

  publish-tauri:
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Just
        uses: extractions/setup-just@6e1de3cc407de738551abd6c0923bd5ed5608042
        with:
          just-version: 1.29.0

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22.2.0
          cache: 'npm'

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Dependencies
        run: |
          just prepare

      - uses: tauri-apps/tauri-action@41242bd545b6d1310ffc1685fb8bb87e97f0b748 # v0.5.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          includeDebug: true
          tagName: ${{ inputs.tag }}
          releaseId: ${{ inputs.id }}
          tauriScript: just ck3oop-ui::tauri
          args: ${{ matrix.args }}
