name: "Test: UI E2E Windows"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
  workflow_dispatch:

env:
  JUST_UNSTABLE: true

jobs:

  test:
    runs-on: windows-latest
    name: "Run UI E2E tests"
    env:
      # xvfb is slow to start
      NODE_TEST_TIMEOUT: 90000
      NODE_TEST_LOGLEVEL: debug
      TAURI_WEBDRIVER_LOGLEVEL: debug

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Just
        uses: extractions/setup-just@6e1de3cc407de738551abd6c0923bd5ed5608042
        with:
          just-version: 1.29.0

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22.2.0
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Prerequisites
        shell: "powershell"
        # https://github.com/actions/runner-images/issues/9538
        # https://github.com/microsoft/playwright/pull/30009/files
        # https://github.com/tauri-apps/wry/issues/1268
        # Evergreen Bootstrapper
        # The Bootstrapper is a tiny installer that downloads
        # the Evergreen Runtime matching device architecture
        # and installs it locally.
        # https://developer.microsoft.com/en-us/microsoft-edge/webview2/consumer/?form=MA13LH
        run: |
          Invoke-WebRequest -Uri 'https://go.microsoft.com/fwlink/p/?LinkId=2124703' -OutFile 'setup.exe'
          Start-Process -FilePath setup.exe -Verb RunAs -Wait

      - name: Run UI E2E tests
        shell: "bash"
        run: |
          just prepare
          just tests-e2e::run
